% PROM_spine_momentum_derivatives
%
% Synthax:
% der = PROM_spine_momentum_derivatives(q,qd,qdd,eta0,xi,tensors)
%
% Description: This function returns the partial derivatives of the change
% in the fish momentum, which is understood as a force acting on the spine.
% The partial derivatives are needed to solve the sensitivity ODE as well 
% as the EoMs.
%
% INPUTS: 
% (1) q:                vector of time domain displacements
% (2) qd:               vector of time domain velocities
% (3) qdd:              vector of time domain acceleration
% (4) xi:               shape variation parameter vector/scalar
% (5) tensors:          tensors (struct) used to express the spine momentum
%                       change
%
% OUTPUTS:
% (1) der:              strucure array containing the partial derivatives 
%     
% Additional notes:
%   - q,qd, qdd should be understood as eta and dot{eta}, ddot{eta}.
%
% Last modified: 13/10/2023, Mathieu Dubied, ETH Zürich
function der = PROM_spine_momentum_derivatives(q,qd,qdd,xi,tensors)
       
    % get tensors   
    Txx = tensors.Txx;
    TxV = tensors.TxV;
    TVx = tensors.TVx;
    TVV = tensors.TVV;
    TUV = tensors.TUV;
    TVU = tensors.TVU;
    TUU = tensors.TUU;
    TxU = tensors.TxU;
    TUx = tensors.TUx;

    % dfdp ________________________________________________________________
    dfdp = ttv(TxU,qdd,2) ...
         + ttv(TUx,qdd,2) ...
         + ttv(ttv(TUU,xi,4),qdd,2) ...
         + ttv(ttv(TUU,xi,3),qdd,2) ...
         + ttv(ttv(TUV,q,4),qdd,2) ...
         + ttv(ttv(TVU,q,3),qd,2) ...
         + ttv(ttv(TVU,qd,3),qd,2) ...
         + ttv(ttv(TUV,qd,4),qd,2);
    
    % dfdq ________________________________________________________________
    dfdq = ttv(TxV,qdd,2) ...
         + ttv(ttv(TUV,xi,3),qdd,2) ...
         + ttv(TVx,qdd,2) ...
         + ttv(ttv(TVU,xi,4),qdd,2) ...
         + ttv(ttv(TVV,q,4),qdd,2) ...
         + ttv(ttv(TVV,q,3),qdd,2) ...
         + ttv(ttv(TVV,qd,3),qd,2) ...
         + ttv(ttv(TVV,qd,4),qd,2);
    
    % dfdqd _______________________________________________________________
    dfdqd = ttv(TVx,qd,3) ...
            + ttv(TVx,qd,2) ...
            + ttv(ttv(TVU,xi,4),qd,3) ...
            + ttv(ttv(TVU,xi,4),qd,2) ...
            + ttv(ttv(TVV,q,4),qd,3) ...
            + ttv(ttv(TVV,q,4),qd,2) ...
            + ttv(TxV,qd,3) ...
            + ttv(TxV,qd,2) ...
            + ttv(ttv(TUV,qd,4),xi,3) ...
            + ttv(ttv(TUV,xi,3),qd,2) ...
            + ttv(ttv(TVV,qd,4),q,3) ...
            + ttv(ttv(TVV,q,3),qd,2);
            

    % dfdqdd ______________________________________________________________
    dfdqdd = Txx ...
            + ttv(TxU,xi,3) ...
            + ttv(TxV,q,3) ...
            + ttv(TUx,xi,3) ...
            + ttv(ttv(TUU,xi,4),xi,3) ...
            + ttv(ttv(TUV,q,4),xi,3) ...
            + ttv(TVx,q,3) ...
            + ttv(ttv(TVU,xi,4),q,3) ...
            + ttv(ttv(TVV,q,4),q,3);
 
    
    % store results in output struct ______________________________________
    der.dfdp = double(dfdp);
    der.dfdq = double(dfdq);
    der.dfdqd = double(dfdqd);
    der.dfdqdd = double(dfdqdd);
   
end
