% derivatives_actuation_force_6
%
% Syntax: derivatives_actuation_force_6(k,t,q,B1T,B2T,B1B,B2B,p)
%
% Description: function producing the derivatives of the actuation force 6
% described in the paper
%
% Last modified: 11/05/2024, Mathieu Dubied, ETH Zürich
function der = derivatives_actuation_force_6(k,t,q,B1T,B2T,B1B,B2B,p)
    p1 = p(1);  % amplitude
    p2 = p(2);  % frequency
    p3 = p(3);  % quantity of easing

    dfdp = [-(1-p3)*cos(pi*(p2*t-0.5))*(B1T+B2T*q) + ...
            - p3*cos(pi*(cos(pi*(p2*t-0.5))-1)/2)*(B1T+B2T*q) + ...
            (1-p3)*cos(pi*(p2*t-0.5))*(B1B+B2B*q) + ...
            p3*cos(pi*(cos(pi*(p2*t-0.5))-1)/2)*(B1B+B2B*q), ...
            p1*((1-p3)*sin(pi*(p2*t-0.5))*pi*t*(B1T+B2T*q) + ...
            - p1*p3*sin(pi*(cos(pi*(p2*t-0.5))-1)/2)*...
            pi*(sin(pi*(p2*t-0.5))-1)/2*...
            pi*t*(B1T+B2T*q) + ...   
            -p1*(1-p3)*sin(pi*(p2*t-0.5))*pi*t*(B1B+B2B*q) + ...       
            p1*p3*sin(pi*(cos(pi*(p2*t-0.5))-1)/2)*...
            pi*(sin(pi*(p2*t-0.5))-1)/2*...
            pi*t*(B1B+B2B*q)), ...
            p1*(cos(pi*(p2*t-0.5))*(B1T+B2T*q) + ...
            - p1*cos(pi*(cos(pi*(p2*t-0.5))-1)/2)*(B1T+B2T*q) + ...
            - p1*cos(pi*(p2*t-0.5))*(B1B+B2B*q) + ...
            p1*cos(pi*(cos(pi*(p2*t-0.5))-1)/2)*(B1B+B2B*q))];
    der.dfdp = k/2*dfdp;
end